CREATE TABLE "admins" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "admins_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "certificates" (
	"id" serial PRIMARY KEY NOT NULL,
	"report_number" text NOT NULL,
	"report_date" timestamp NOT NULL,
	"shape" text NOT NULL,
	"measurements" text NOT NULL,
	"carat_weight" numeric(6, 3) NOT NULL,
	"color_grade" text NOT NULL,
	"clarity_grade" text NOT NULL,
	"cut_grade" text NOT NULL,
	"polish" text NOT NULL,
	"symmetry" text NOT NULL,
	"fluorescence" text NOT NULL,
	"inscription" text,
	"comments" text,
	"gemologist_name" text NOT NULL,
	"signature_date" timestamp NOT NULL,
	"reference_number" text,
	"filename" text,
	"gem_image_path" text,
	"gem_type" text DEFAULT 'Diamond',
	"dimensions" text,
	"treatment" text,
	"origin" text,
	"certification_date" text,
	"examined_by" text,
	"approved_by" text,
	"lab_location" text,
	"equipment_used" text,
	"table_percentage" text,
	"depth_percentage" text,
	"crown_angle" text,
	"pavilion_angle" text,
	"girdle_thickness" text,
	"culet_size" text,
	"laser_inscription" text,
	"photo_included" boolean DEFAULT false,
	"plot_diagram" boolean DEFAULT false,
	"digitally_signed_by" boolean DEFAULT false,
	"color_grade_diagram" boolean DEFAULT false,
	"clarity_plot_diagram" boolean DEFAULT false,
	"certificate_notes" text,
	"verifier_url" text DEFAULT 'https://gilab.info/verify',
	"proportions_diagram" text,
	"clarity_diagram1" text,
	"clarity_diagram2" text,
	"issue_date" timestamp DEFAULT now(),
	"upload_date" timestamp DEFAULT now(),
	"is_active" boolean DEFAULT true,
	CONSTRAINT "certificates_report_number_unique" UNIQUE("report_number")
);
